apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    resources: {}
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
    -  name: SECRET_PASSWORD
       valueFrom:
        secretKeyRef:
          key: password 
  restartPolicy: Never