apiVersion: v1
kind: PersistentVolume
metadata:
  name: clarus-pv-vol
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/c/Users/seraf/OneDrive/Masaüstü/Kubernetes-Work/Kubernetes-3/pv-data"

  