apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-vol
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/home/ubuntu/pv-data"

